# Generated by Django 6.0.1 on 2026-02-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(choices=[('BOGOTA', 'Bogota'), ('MEDELLIN', 'Medellin'), ('CALI', 'Cali')], default='BOGOTA', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ciudad',
            field=models.CharField(choices=[('BOGOTA', 'Bogota'), ('MEDELLIN', 'Medellin'), ('CALI', 'Cali')], default='BOGOTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('comercial', 'Comercial'), ('logistica', 'Logística'), ('programador', 'Programador')], max_length=20),
        ),
    ]
