# Generated by Django 6.0.2 on 2026-02-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_pedido_ciudad_perfilusuario_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
