# Generated by Django 6.0.2 on 2026-02-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_perfilusuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15),
        ),
    ]
