# Generated by Django 6.0.2 on 2026-02-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='presentacion',
            field=models.CharField(choices=[('OV20_1000', 'OV20 - 1000g'), ('OV15_200', 'OV15 - 200g'), ('SAC_20', 'Saco 20kg'), ('SAC_5', 'Saco 5kg')], default='OV20_1000', max_length=20),
        ),
    ]
