# Generated by Django 6.0.2 on 2026-02-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_proveedor_presentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(choices=[('BOGOTA', 'Bogota'), ('MEDELLIN', 'Medellin'), ('CALI', 'Cali')], default='BOGOTA', max_length=20),
        ),
    ]
