# Generated by Django 6.0.2 on 2026-02-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_proveedor_contacto_remove_proveedor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(default='Proveedor sin nombre', max_length=150),
        ),
    ]
