# Generated by Django 6.0.2 on 2026-02-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_proveedor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='presentacion',
            field=models.CharField(choices=[('OV20_1000', 'OV20 1000'), ('OV15_200', 'OV15 200'), ('OV15_20', 'OV15 20'), ('OV15_15', 'OV15 15'), ('OV15_14', 'OV15 14'), ('OV30_20', 'OV30-20'), ('OV30_10', 'OV30-10'), ('OV30_5', 'OV30-5'), ('OV30_3', 'OV30-3'), ('SAC_20', 'Sac x 20'), ('BOLSA_4_4KG', 'Bolsa 4,4Kg')], max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='presentacion',
            field=models.CharField(choices=[('OV20_1000', 'OV20 1000'), ('OV15_200', 'OV15 200'), ('OV15_20', 'OV15 20'), ('OV15_15', 'OV15 15'), ('OV15_14', 'OV15 14'), ('OV30_20', 'OV30-20'), ('OV30_10', 'OV30-10'), ('OV30_5', 'OV30-5'), ('OV30_3', 'OV30-3'), ('SAC_20', 'Sac x 20'), ('BOLSA_4_4KG', 'Bolsa 4,4Kg')], default='OV20_1000', max_length=20),
        ),
    ]
