# Generated by Django 6.0.1 on 2026-02-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_notificacion_reproducir_sonido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroestadopedido',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo_evento',
            field=models.CharField(choices=[('INFO', 'Informacion'), ('PEDIDO_CREADO', 'Pedido creado'), ('PEDIDO_CONFIRMADO', 'Pedido confirmado'), ('PEDIDO_CANCELADO', 'Pedido cancelado'), ('PEDIDO_DEVUELTO', 'Pedido devuelto'), ('PEDIDO_CAMBIO_ESTADO', 'Cambio de estado')], default='INFO', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_PRODUCCION', 'En produccion'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('DEVUELTO', 'Devuelto')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('comercial', 'Comercial'), ('logistica', 'Logistica'), ('produccion', 'Produccion'), ('programador', 'Programador')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registroestadopedido',
            name='estado_anterior',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_PRODUCCION', 'En produccion'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('DEVUELTO', 'Devuelto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registroestadopedido',
            name='estado_nuevo',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_PRODUCCION', 'En produccion'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('DEVUELTO', 'Devuelto')], max_length=20),
        ),
    ]
