# Generated by Django 6.0.2 on 2026-02-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_materiaprima'),
        ('clientes', '0010_registroestadopedido_descripcion_and_more'),
    ]

    operations = [
    ]
