# Generated by Django 6.0.2 on 2026-02-20 21:20

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_merge_20260220_0835'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregapedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado')], db_index=True, default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='entregapedido',
            name='fecha_entrega',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='fecha',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='tipo_huevo',
            field=models.CharField(choices=[('HELU', 'Huevo Líquido Entero'), ('YELU', 'Yema Líquida'), ('CLLU', 'Clara Líquida'), ('MEPU', 'Mezcla en Polvo')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='reproducir_sonido',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(choices=[('BOGOTA', 'Bogota'), ('MEDELLIN', 'Medellin'), ('CALI', 'Cali')], db_index=True, default='BOGOTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_PRODUCCION', 'En produccion'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('DEVUELTO', 'Devuelto')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='presentacion',
            field=models.CharField(choices=[('OV20_1000', 'OV20 1000'), ('OV15_200', 'OV15 200'), ('OV15_20', 'OV15 20'), ('OV15_15', 'OV15 15'), ('OV15_14', 'OV15 14'), ('OV30_20', 'OV30-20'), ('OV30_10', 'OV30-10'), ('OV30_5', 'OV30-5'), ('OV30_3', 'OV30-3'), ('SAC_20', 'Sac x 20'), ('BOLSA_4_4KG', 'Bolsa 4,4Kg')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='semana',
            field=models.DateField(blank=True, db_index=True, help_text='Lunes de la semana', null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_huevo',
            field=models.CharField(choices=[('HELU', 'Huevo Líquido Entero'), ('YELU', 'Yema Líquida'), ('CLLU', 'Clara Líquida'), ('MEPU', 'Mezcla en Polvo')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='registroestadopedido',
            name='estado_nuevo',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_PRODUCCION', 'En produccion'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('DEVUELTO', 'Devuelto')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='registroestadopedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='entregapedido',
            index=models.Index(fields=['pedido', 'fecha_entrega'], name='clientes_en_pedido__bfe524_idx'),
        ),
        migrations.AddIndex(
            model_name='entregapedido',
            index=models.Index(fields=['estado', 'fecha_entrega'], name='clientes_en_estado_ecc9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='materiaprima',
            index=models.Index(fields=['fecha', 'tipo_huevo'], name='clientes_ma_fecha_a57ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leida', 'fecha_creacion'], name='clientes_no_usuario_b5bd09_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'reproducir_sonido', 'fecha_creacion'], name='clientes_no_usuario_a1833a_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='clientes_pe_estado_2cafdd_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['semana', 'estado'], name='clientes_pe_semana_d6dab1_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['ciudad', 'estado'], name='clientes_pe_ciudad_a06587_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['semana', 'presentacion', 'tipo_huevo'], name='clientes_pe_semana_3f7704_idx'),
        ),
        migrations.AddIndex(
            model_name='registroestadopedido',
            index=models.Index(fields=['estado_nuevo', 'fecha_creacion'], name='clientes_re_estado__a43ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='registroestadopedido',
            index=models.Index(fields=['pedido', 'fecha_creacion'], name='clientes_re_pedido__5a224b_idx'),
        ),
    ]
