# Generated by Django 6.0.2 on 2026-02-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_alter_entregapedido_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='tipo_huevo',
            field=models.CharField(choices=[('HELU', 'Huevo Líquido Entero'), ('YELU', 'Yema Líquida'), ('CLLU', 'Clara Líquida'), ('MEPU', 'Mezcla en Polvo'), ('HEPU', 'Huevo en Polvo'), ('YEPU', 'Yema en Polvo'), ('ALBP', 'Albumina en Polvo')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_huevo',
            field=models.CharField(choices=[('HELU', 'Huevo Líquido Entero'), ('YELU', 'Yema Líquida'), ('CLLU', 'Clara Líquida'), ('MEPU', 'Mezcla en Polvo'), ('HEPU', 'Huevo en Polvo'), ('YEPU', 'Yema en Polvo'), ('ALBP', 'Albumina en Polvo')], db_index=True, max_length=10),
        ),
    ]
