# Generated by Django 6.0.2 on 2026-02-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_alter_materiaprima_tipo_huevo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='presentacion',
            field=models.CharField(choices=[('OV20_1000', 'OV20 1000'), ('OV20_20', 'OV20 x 20'), ('OV20_15', 'OV20 x 15'), ('OV15_200', 'OV15 200'), ('OV15_20', 'OV15 20'), ('OV15_15', 'OV15 15'), ('OV15_14', 'OV15 14'), ('OV30_20', 'OV30-20'), ('OV30_10', 'OV30-10'), ('OV30_5', 'OV30-5'), ('OV30_3', 'OV30-3'), ('OV30_3KG', 'OV30 x 3Kg'), ('SAC_20', 'Sac x 20'), ('BOLSA_4_4KG', 'Bolsa 4,4Kg'), ('POLVO_DOSIF_2KG', 'Polvo dosificado 2 kilos')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='presentacion',
            field=models.CharField(choices=[('OV20_1000', 'OV20 1000'), ('OV20_20', 'OV20 x 20'), ('OV20_15', 'OV20 x 15'), ('OV15_200', 'OV15 200'), ('OV15_20', 'OV15 20'), ('OV15_15', 'OV15 15'), ('OV15_14', 'OV15 14'), ('OV30_20', 'OV30-20'), ('OV30_10', 'OV30-10'), ('OV30_5', 'OV30-5'), ('OV30_3', 'OV30-3'), ('OV30_3KG', 'OV30 x 3Kg'), ('SAC_20', 'Sac x 20'), ('BOLSA_4_4KG', 'Bolsa 4,4Kg'), ('POLVO_DOSIF_2KG', 'Polvo dosificado 2 kilos')], default='OV20_1000', max_length=20),
        ),
    ]
