# Generated by Django 5.1.6 on 2026-02-27 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_pedido_despachado_kg_pedido_fabricado_kg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('FABRICADO_ACTUALIZADO', 'Fabricado actualizado'), ('ESTADO_EN_PRODUCCION', 'Cambio a en produccion'), ('MATERIA_PRIMA_REGISTRADA', 'Materia prima registrada')], db_index=True, max_length=40)),
                ('sucursal', models.CharField(blank=True, default='', max_length=20)),
                ('compania', models.CharField(blank=True, default='', max_length=150)),
                ('tipo_huevo', models.CharField(blank=True, default='', max_length=80)),
                ('presentacion', models.CharField(blank=True, default='', max_length=80)),
                ('valor_anterior', models.IntegerField(blank=True, null=True)),
                ('valor_nuevo', models.IntegerField(blank=True, null=True)),
                ('cantidad_kg', models.IntegerField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_produccion', to='clientes.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_produccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
                'indexes': [models.Index(fields=['accion', 'fecha_creacion'], name='clientes_re_accion_762f03_idx'), models.Index(fields=['sucursal', 'fecha_creacion'], name='clientes_re_sucursa_18bc4b_idx'), models.Index(fields=['pedido', 'fecha_creacion'], name='clientes_re_pedido__a42ddf_idx')],
            },
        ),
    ]
