# Generated by Django 6.0.2 on 2026-03-05 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_pedido_estimado_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimadoSemanalProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.DateField(db_index=True, help_text='Lunes de la semana')),
                ('sucursal', models.CharField(choices=[('BOGOTA', 'Bogota'), ('MEDELLIN', 'Medellin'), ('CALI', 'Cali')], db_index=True, max_length=20)),
                ('presentacion', models.CharField(choices=[('OV20_1000', 'OV20 1000'), ('OV20_20', 'OV20 x 20'), ('OV20_15', 'OV20 x 15'), ('OV15_200', 'OV15 200'), ('OV15_20', 'OV15 20'), ('OV15_15', 'OV15 15'), ('OV15_14', 'OV15 14'), ('OV30_20', 'OV30-20'), ('OV30_10', 'OV30-10'), ('OV30_5', 'OV30-5'), ('OV30_3', 'OV30-3'), ('OV30_3KG', 'OV30 x 3Kg'), ('SAC_20', 'Sac x 20'), ('BOLSA_4_4KG', 'Bolsa 4,4Kg'), ('POLVO_DOSIF_2KG', 'Polvo dosificado 2 kilos')], db_index=True, max_length=20)),
                ('cantidad_kg', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimados_semanales_actualizados', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimados_semanales', to='clientes.proveedor')),
            ],
            options={
                'ordering': ['-semana', 'sucursal', 'proveedor__nombre'],
                'indexes': [models.Index(fields=['semana', 'sucursal'], name='clientes_es_semana_fc7155_idx'), models.Index(fields=['semana', 'presentacion'], name='clientes_es_semana_9ae7eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('semana', 'sucursal', 'proveedor'), name='unique_estimado_semanal_proveedor_sucursal')],
            },
        ),
    ]
