# Generated by Django 5.1.6 on 2026-03-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_estimadosemanalproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('comercial', 'Comercial'), ('auxiliar', 'Auxiliar'), ('logistica', 'Logistica'), ('produccion', 'Produccion'), ('programador', 'Programador')], max_length=20),
        ),
    ]
